name: Publish to NuGet

on:
  push:
    tags:
      - 'v*.*.*'

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  publish:
    name: Publish to NuGet
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Fetch all tags
      run: git fetch --force --tags

    - name: Verify tags
      run: |
        echo "Current commit: $(git rev-parse HEAD)"
        echo "Tags at this commit: $(git tag --points-at HEAD)"
        echo "All tags: $(git tag -l)"

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Check MinVer version
      run: |
        echo "Checking what version MinVer calculated..."
        dotnet msbuild src/Cloudvelous.Aws.Core/Cloudvelous.Aws.Core.csproj -getProperty:Version -nologo

    - name: Test
      run: dotnet test --no-build --configuration Release

    - name: Pack with MinVer versioning
      run: dotnet pack --no-build --configuration Release --output ./artifacts

    - name: Publish to NuGet.org
      run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
